$axure.loadCurrentPage({
  "url":"管理页面.html",
  "generationDate":new Date(1597890169283.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"94b711de781e4409ab6d8685717a10da",
    "type":"Axure:Page",
    "name":"管理页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"67f3631691a6488c8ec33f5ab26f47bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1920,
              "height":1080}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c1cd38b79394cd2b2076b53ec88d819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1920,
                  "height":1080}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u0.png"}},
{
          "id":"39828b6b00df452d92320faa9f88f6a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "size":{
              "width":404,
              "height":1080}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dac5ddbb1b92482eafc557764a54dca8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "size":{
                  "width":404,
                  "height":1080}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u2.png"}},
{
          "id":"3ef6a98ec0544966a0277add3e22a634",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":64},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f56422b7012b48b8968867d92bc81761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":64},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e22b9dd0f1cf43958cbe2d8462c629a3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":404,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/展示页面/u6_line.png"}},
{
          "id":"b02dbbf4e10541fb9173c540465e644d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":404,
              "y":0},
            "size":{
              "width":1516,
              "height":80},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9a3c2f7063b4ee59cbf3444826ca363",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":404,
                  "y":0},
                "size":{
                  "width":1516,
                  "height":80},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u7.png"}},
{
          "id":"2e1ea0c0e8bb47c194705f96cb563b10",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1632,
              "y":25},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54382663e7a249c0a5928fc25169c4b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1632,
                  "y":25},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u14.png"}},
{
          "id":"b079861de61b45c1a2c0a44eb98c08b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1715,
              "y":25},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7a4e629e2240d3a75a60b375f9b4ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1715,
                  "y":25},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u16.png"}},
{
          "id":"7b0daa36cc2046afb89a9ea54a3e334f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1798,
              "y":25},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"576588bb1a2a425686fa60db7679295e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1798,
                  "y":25},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u18.png"}},
{
          "id":"896c8fc947474b41b51f2a98b5e98a71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":404,
              "y":80},
            "size":{
              "width":1516,
              "height":1000},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ab10a67857c492994553f1a3fa8afbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":404,
                  "y":80},
                "size":{
                  "width":1516,
                  "height":1000},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u56.png"}},
{
          "id":"e2d79a81dd2147b0a0542218fb69898a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4,
              "opacity":1},
            "location":{
              "x":140,
              "y":32},
            "size":{
              "width":197,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a04414981dfa4bc28179dfe6107948f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":32},
                "size":{
                  "width":197,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d10cfb65bdbb4a988c03bbaa91f0f0a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":38},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3f30be78b44f50a541ba26748b5938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":38},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u60.png"}},
{
          "id":"54b8f1ed41144ee9a0182f564626a8da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":432,
              "y":18},
            "size":{
              "width":88,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5856b9a1d879430eb7fcb54fec60550c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":432,
                  "y":18},
                "size":{
                  "width":88,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 展示页面",
                      "target":{
                        "targetType":"page",
                        "url":"展示页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"154222f84ec548ab8f0dc70a9a24f89c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "hint":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":708,
              "y":20},
            "size":{
              "width":302,
              "height":38}},
          "adaptiveStyles":{
},
          "placeholderText":" Search"},
{
          "id":"4a2b78eb71b344d19e01dc1eb04e6e79",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":974,
              "y":25},
            "size":{
              "width":28,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"018ca31226c14e5fa7ca29e7fb48a7f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":974,
                  "y":25},
                "size":{
                  "width":28,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/展示页面/u12.png"}},
{
          "id":"05b7d514b7f54a5d9d3b51e46967d476",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"30px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":542,
              "y":18},
            "size":{
              "width":112,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f28d05c1bd3423fa2df781d5c90beab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"30px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":542,
                  "y":18},
                "size":{
                  "width":112,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e78a761535984d45b5c642948da6916c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":137}},
          "adaptiveStyles":{
},
          "masterId":"1ca8e3e396a7459b8fb99134ddfbd335"}]}},
  "masters":{
    "1ca8e3e396a7459b8fb99134ddfbd335":{
      "packageId":"1ca8e3e396a7459b8fb99134ddfbd335",
      "type":"Axure:Master",
      "name":"left_menu-gl",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ff2bc935a97642838d843b900b5392f2",
            "label":"",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":404,
                "height":943}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"dd57f8751e564bdc853edc1ee2395282",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"863cd8e30dbf4a34b17217e5c8661476",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "size":{
                        "width":404,
                        "height":943},
                      "linePattern":"none"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8ab6ca1111084f0b934af2fb5aa353ce",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "size":{
                            "width":404,
                            "height":943},
                          "linePattern":"none"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/展示页面/u22.png"}},
{
                    "id":"183de699c4ce498aafa4d1f9c1f60c80",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF666666},
                      "location":{
                        "x":17,
                        "y":10},
                      "size":{
                        "width":370,
                        "height":50},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0481752f3644494a808529f21583d538",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF666666},
                          "location":{
                            "x":17,
                            "y":10},
                          "size":{
                            "width":370,
                            "height":50},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u24.png"}},
{
                    "id":"0b1c620136f1445393cbb92c88deca76",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":38,
                        "y":20},
                      "size":{
                        "width":30,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d76cf230fe594409bfc1065b41e59de5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":38,
                            "y":20},
                          "size":{
                            "width":30,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/管理页面/u34.png"}},
{
                    "id":"ac7a5fb3b50844a692110018c01add84",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Bold', '微软雅黑'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontSize":"20px",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":17,
                        "y":60},
                      "size":{
                        "width":370,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"019fb3100cc44fc9811cf7543e6db21f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Bold', '微软雅黑'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontSize":"20px",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF000000,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":17,
                            "y":60},
                          "size":{
                            "width":370,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u28.png",
                      "mouseOver~":"images/展示页面/u28_mouseOver.png"}},
{
                    "id":"de327a6f88f3416fa90f7befb09ee56d",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "location":{
                        "x":81,
                        "y":24},
                      "size":{
                        "width":73,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4ce461c424ac4b8c9152e28527b224e8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "location":{
                            "x":81,
                            "y":24},
                          "size":{
                            "width":73,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"77819f2a15f34082a0abfebf56cafda8",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":346,
                        "y":30},
                      "size":{
                        "width":20,
                        "height":10}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"1cdd413745a844ea8bb033c1b44d2586",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":346,
                            "y":30},
                          "size":{
                            "width":20,
                            "height":10}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/展示页面/u34.png"}},
{
                    "id":"cdf1ac89ffa040e282243e2ec01bc052",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF666666},
                      "location":{
                        "x":17,
                        "y":100},
                      "size":{
                        "width":370,
                        "height":50},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6528e6886c1e4a0f87dec058f79cdbeb",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF666666},
                          "location":{
                            "x":17,
                            "y":100},
                          "size":{
                            "width":370,
                            "height":50},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u24.png"}},
{
                    "id":"0eeac66c30364e26aa9a41a34e0cdf96",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":38,
                        "y":110},
                      "size":{
                        "width":30,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fed28f1b39e648309dd6e4cb5454351e",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":38,
                            "y":110},
                          "size":{
                            "width":30,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/管理页面/u44.png"}},
{
                    "id":"3893ea3aac1d4894b1231577ca1ecba2",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Bold', '微软雅黑'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontSize":"20px",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":17,
                        "y":150},
                      "size":{
                        "width":370,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"feb18bb576cd42188c56be3d93884fda",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Bold', '微软雅黑'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontSize":"20px",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF000000,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":17,
                            "y":150},
                          "size":{
                            "width":370,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u28.png",
                      "mouseOver~":"images/展示页面/u28_mouseOver.png"}},
{
                    "id":"ca2adb10622d4248a0f0f0901ca63f35",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "location":{
                        "x":81,
                        "y":114},
                      "size":{
                        "width":127,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"ebd47884eb004a97be12deddc8cc7c68",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "location":{
                            "x":81,
                            "y":114},
                          "size":{
                            "width":127,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"63f6c117f5fb41609f46115a8aa825e1",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":346,
                        "y":120},
                      "size":{
                        "width":20,
                        "height":10}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"389fa716367d48b481cbb502f6e53973",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":346,
                            "y":120},
                          "size":{
                            "width":20,
                            "height":10}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/展示页面/u34.png"}},
{
                    "id":"955a6550a2064b23af0a5b1d578f613e",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF666666},
                      "location":{
                        "x":17,
                        "y":280},
                      "size":{
                        "width":370,
                        "height":50},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"521b07d6d43043b78e3b21ad3413fdde",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF666666},
                          "location":{
                            "x":17,
                            "y":280},
                          "size":{
                            "width":370,
                            "height":50},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u24.png"}},
{
                    "id":"a044688b305640528dbedde70c3f1d3c",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":38,
                        "y":290},
                      "size":{
                        "width":30,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4e03918481884eafbe7ac05f7b05f679",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":38,
                            "y":290},
                          "size":{
                            "width":30,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/管理页面/u54.png"}},
{
                    "id":"6a71fde5f078493a964c5372007c3c0d",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Bold', '微软雅黑'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontSize":"20px",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":17,
                        "y":330},
                      "size":{
                        "width":370,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d9fd77f683c4483ba29921640de30bc8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Bold', '微软雅黑'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontSize":"20px",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF000000,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":17,
                            "y":330},
                          "size":{
                            "width":370,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 用户管理",
                                "target":{
                                  "targetType":"page",
                                  "url":"用户管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u28.png",
                      "mouseOver~":"images/展示页面/u28_mouseOver.png"}},
{
                    "id":"d056b51e4411460f92688d304b95b377",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "location":{
                        "x":81,
                        "y":294},
                      "size":{
                        "width":73,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6c694f04999048b8bc986dee0e640d8a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "location":{
                            "x":81,
                            "y":294},
                          "size":{
                            "width":73,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"baf85f0996f94f9782ea1ba9d7d41b54",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":346,
                        "y":300},
                      "size":{
                        "width":20,
                        "height":10}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2c7be40c096f4cc59b0c2d666c30a60f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":346,
                            "y":300},
                          "size":{
                            "width":20,
                            "height":10}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/展示页面/u34.png"}},
{
                    "id":"30e181cb87354d90a3ef6b4eb079aed0",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF666666},
                      "location":{
                        "x":17,
                        "y":190},
                      "size":{
                        "width":370,
                        "height":50},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2e5167992ade4b5d975ed5a1ef187b0d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF666666},
                          "location":{
                            "x":17,
                            "y":190},
                          "size":{
                            "width":370,
                            "height":50},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u24.png"}},
{
                    "id":"f92ec1ea40454432a3611870c51d1289",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":38,
                        "y":200},
                      "size":{
                        "width":30,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"fc75d2e70626404499a1f915e73f2e8c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":38,
                            "y":200},
                          "size":{
                            "width":30,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/管理页面/u64.png"}},
{
                    "id":"7c1e7c395bac42d794e0bd6c7201e85e",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Bold', '微软雅黑'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontSize":"20px",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":17,
                        "y":240},
                      "size":{
                        "width":370,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"7a4f95715f17404eabc4337654299353",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Bold', '微软雅黑'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontSize":"20px",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF000000,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":17,
                            "y":240},
                          "size":{
                            "width":370,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u28.png",
                      "mouseOver~":"images/展示页面/u28_mouseOver.png"}},
{
                    "id":"ca531095c68c4624833bf211199284de",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'Arial Negreta', 'Arial'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "location":{
                        "x":81,
                        "y":204},
                      "size":{
                        "width":127,
                        "height":22}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e07bc8b5dc6344dab4e43981c039184f",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Arial Negreta', 'Arial'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "location":{
                            "x":81,
                            "y":204},
                          "size":{
                            "width":127,
                            "height":22}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"60aef59d184d47de8688f024840b8a2a",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":346,
                        "y":210},
                      "size":{
                        "width":20,
                        "height":10}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"c8bca63596d04bf8b56e591bb8983d53",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":346,
                            "y":210},
                          "size":{
                            "width":20,
                            "height":10}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/展示页面/u34.png"}},
{
                    "id":"6527389da68544c08f5d1fa465022fbc",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Bold', '微软雅黑'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontSize":"20px",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":17,
                        "y":370},
                      "size":{
                        "width":370,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8c3f3e74d79d43e3a43455d599cc443b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Bold', '微软雅黑'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontSize":"20px",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF000000,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":17,
                            "y":370},
                          "size":{
                            "width":370,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 功能管理",
                                "target":{
                                  "targetType":"page",
                                  "url":"功能管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u28.png",
                      "mouseOver~":"images/展示页面/u28_mouseOver.png"}},
{
                    "id":"9378a4214fc54e97a4ce335c47004bde",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Bold', '微软雅黑'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontSize":"20px",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":17,
                        "y":410},
                      "size":{
                        "width":370,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"bd9769ae0a9449f68520286aa257e684",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Bold', '微软雅黑'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontSize":"20px",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF000000,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":17,
                            "y":410},
                          "size":{
                            "width":370,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 角色管理",
                                "target":{
                                  "targetType":"page",
                                  "url":"角色管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u28.png",
                      "mouseOver~":"images/展示页面/u28_mouseOver.png"}},
{
                    "id":"8013428eb8504075b7301257f8b7d81b",
                    "label":"",
                    "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Bold', '微软雅黑'",
                      "fontSize":"18px",
                      "fontWeight":"700",
                      "horizontalAlignment":"left",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "stateStyles":{
                        "mouseOver":{
                          "fontSize":"20px",
                          "fontWeight":"bold",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFF000000,
                            "opacity":1},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF}}},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF000000},
                      "location":{
                        "x":17,
                        "y":450},
                      "size":{
                        "width":370,
                        "height":40},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "cornerRadiusTopLeft":"8"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0d347075a7cb43209a80ddaf71eeed93",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ff2bc935a97642838d843b900b5392f2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Bold', '微软雅黑'",
                          "fontSize":"18px",
                          "fontWeight":"700",
                          "horizontalAlignment":"left",
                          "foreGroundFill":{
                            "fillType":"solid",
                            "color":0xFFFFFFFF,
                            "opacity":1},
                          "stateStyles":{
                            "mouseOver":{
                              "fontSize":"20px",
                              "fontWeight":"bold",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFF000000,
                                "opacity":1},
                              "fill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF}}},
                          "fill":{
                            "fillType":"solid",
                            "color":0xFF000000},
                          "location":{
                            "x":17,
                            "y":450},
                          "size":{
                            "width":370,
                            "height":40},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "cornerRadiusTopLeft":"8"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 日志管理",
                                "target":{
                                  "targetType":"page",
                                  "url":"日志管理.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/展示页面/u28.png",
                      "mouseOver~":"images/展示页面/u28_mouseOver.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "67f3631691a6488c8ec33f5ab26f47bb":{
      "scriptId":"u0"},
    "7c1cd38b79394cd2b2076b53ec88d819":{
      "scriptId":"u1"},
    "39828b6b00df452d92320faa9f88f6a8":{
      "scriptId":"u2"},
    "dac5ddbb1b92482eafc557764a54dca8":{
      "scriptId":"u3"},
    "3ef6a98ec0544966a0277add3e22a634":{
      "scriptId":"u4"},
    "f56422b7012b48b8968867d92bc81761":{
      "scriptId":"u5"},
    "e22b9dd0f1cf43958cbe2d8462c629a3":{
      "scriptId":"u6"},
    "b02dbbf4e10541fb9173c540465e644d":{
      "scriptId":"u7"},
    "d9a3c2f7063b4ee59cbf3444826ca363":{
      "scriptId":"u8"},
    "2e1ea0c0e8bb47c194705f96cb563b10":{
      "scriptId":"u9"},
    "54382663e7a249c0a5928fc25169c4b9":{
      "scriptId":"u10"},
    "b079861de61b45c1a2c0a44eb98c08b2":{
      "scriptId":"u11"},
    "7b7a4e629e2240d3a75a60b375f9b4ca":{
      "scriptId":"u12"},
    "7b0daa36cc2046afb89a9ea54a3e334f":{
      "scriptId":"u13"},
    "576588bb1a2a425686fa60db7679295e":{
      "scriptId":"u14"},
    "896c8fc947474b41b51f2a98b5e98a71":{
      "scriptId":"u15"},
    "3ab10a67857c492994553f1a3fa8afbc":{
      "scriptId":"u16"},
    "e2d79a81dd2147b0a0542218fb69898a":{
      "scriptId":"u17"},
    "a04414981dfa4bc28179dfe6107948f8":{
      "scriptId":"u18"},
    "d10cfb65bdbb4a988c03bbaa91f0f0a7":{
      "scriptId":"u19"},
    "5a3f30be78b44f50a541ba26748b5938":{
      "scriptId":"u20"},
    "54b8f1ed41144ee9a0182f564626a8da":{
      "scriptId":"u21"},
    "5856b9a1d879430eb7fcb54fec60550c":{
      "scriptId":"u22"},
    "154222f84ec548ab8f0dc70a9a24f89c":{
      "scriptId":"u23"},
    "4a2b78eb71b344d19e01dc1eb04e6e79":{
      "scriptId":"u24"},
    "018ca31226c14e5fa7ca29e7fb48a7f7":{
      "scriptId":"u25"},
    "05b7d514b7f54a5d9d3b51e46967d476":{
      "scriptId":"u26"},
    "0f28d05c1bd3423fa2df781d5c90beab":{
      "scriptId":"u27"},
    "e78a761535984d45b5c642948da6916c":{
      "scriptId":"u28",
      "ff2bc935a97642838d843b900b5392f2":{
        "scriptId":"u29"},
      "863cd8e30dbf4a34b17217e5c8661476":{
        "scriptId":"u30"},
      "8ab6ca1111084f0b934af2fb5aa353ce":{
        "scriptId":"u31"},
      "183de699c4ce498aafa4d1f9c1f60c80":{
        "scriptId":"u32"},
      "0481752f3644494a808529f21583d538":{
        "scriptId":"u33"},
      "0b1c620136f1445393cbb92c88deca76":{
        "scriptId":"u34"},
      "d76cf230fe594409bfc1065b41e59de5":{
        "scriptId":"u35"},
      "ac7a5fb3b50844a692110018c01add84":{
        "scriptId":"u36"},
      "019fb3100cc44fc9811cf7543e6db21f":{
        "scriptId":"u37"},
      "de327a6f88f3416fa90f7befb09ee56d":{
        "scriptId":"u38"},
      "4ce461c424ac4b8c9152e28527b224e8":{
        "scriptId":"u39"},
      "77819f2a15f34082a0abfebf56cafda8":{
        "scriptId":"u40"},
      "1cdd413745a844ea8bb033c1b44d2586":{
        "scriptId":"u41"},
      "cdf1ac89ffa040e282243e2ec01bc052":{
        "scriptId":"u42"},
      "6528e6886c1e4a0f87dec058f79cdbeb":{
        "scriptId":"u43"},
      "0eeac66c30364e26aa9a41a34e0cdf96":{
        "scriptId":"u44"},
      "fed28f1b39e648309dd6e4cb5454351e":{
        "scriptId":"u45"},
      "3893ea3aac1d4894b1231577ca1ecba2":{
        "scriptId":"u46"},
      "feb18bb576cd42188c56be3d93884fda":{
        "scriptId":"u47"},
      "ca2adb10622d4248a0f0f0901ca63f35":{
        "scriptId":"u48"},
      "ebd47884eb004a97be12deddc8cc7c68":{
        "scriptId":"u49"},
      "63f6c117f5fb41609f46115a8aa825e1":{
        "scriptId":"u50"},
      "389fa716367d48b481cbb502f6e53973":{
        "scriptId":"u51"},
      "955a6550a2064b23af0a5b1d578f613e":{
        "scriptId":"u52"},
      "521b07d6d43043b78e3b21ad3413fdde":{
        "scriptId":"u53"},
      "a044688b305640528dbedde70c3f1d3c":{
        "scriptId":"u54"},
      "4e03918481884eafbe7ac05f7b05f679":{
        "scriptId":"u55"},
      "6a71fde5f078493a964c5372007c3c0d":{
        "scriptId":"u56"},
      "d9fd77f683c4483ba29921640de30bc8":{
        "scriptId":"u57"},
      "d056b51e4411460f92688d304b95b377":{
        "scriptId":"u58"},
      "6c694f04999048b8bc986dee0e640d8a":{
        "scriptId":"u59"},
      "baf85f0996f94f9782ea1ba9d7d41b54":{
        "scriptId":"u60"},
      "2c7be40c096f4cc59b0c2d666c30a60f":{
        "scriptId":"u61"},
      "30e181cb87354d90a3ef6b4eb079aed0":{
        "scriptId":"u62"},
      "2e5167992ade4b5d975ed5a1ef187b0d":{
        "scriptId":"u63"},
      "f92ec1ea40454432a3611870c51d1289":{
        "scriptId":"u64"},
      "fc75d2e70626404499a1f915e73f2e8c":{
        "scriptId":"u65"},
      "7c1e7c395bac42d794e0bd6c7201e85e":{
        "scriptId":"u66"},
      "7a4f95715f17404eabc4337654299353":{
        "scriptId":"u67"},
      "ca531095c68c4624833bf211199284de":{
        "scriptId":"u68"},
      "e07bc8b5dc6344dab4e43981c039184f":{
        "scriptId":"u69"},
      "60aef59d184d47de8688f024840b8a2a":{
        "scriptId":"u70"},
      "c8bca63596d04bf8b56e591bb8983d53":{
        "scriptId":"u71"},
      "6527389da68544c08f5d1fa465022fbc":{
        "scriptId":"u72"},
      "8c3f3e74d79d43e3a43455d599cc443b":{
        "scriptId":"u73"},
      "9378a4214fc54e97a4ce335c47004bde":{
        "scriptId":"u74"},
      "bd9769ae0a9449f68520286aa257e684":{
        "scriptId":"u75"},
      "8013428eb8504075b7301257f8b7d81b":{
        "scriptId":"u76"},
      "0d347075a7cb43209a80ddaf71eeed93":{
        "scriptId":"u77"}}}});